services:
  research-ai:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: autonomous-research-ai

    ports:
      - "8501:8501"

    env_file:
      - .env

    restart: unless-stopped